services:
    wolfsblvt.onlinetime.listener:
        class: wolfsblvt\onlinetime\event\listener
        arguments:
            - @wolfsblvt.onlinetime.onlinetime
            - @dbal.conn
            - @path_helper
            - @template
            - @user
            - @request
        tags:
            - { name: event.listener }
    wolfsblvt.onlinetime.onlinetime:
        class: wolfsblvt\onlinetime\core\onlinetime
        arguments:
            - @wolfsblvt.onlinetime.formatter
            - @dbal.conn
            - @config
            - @template
            - @user
            - @auth
    wolfsblvt.onlinetime.formatter:
        class: wolfsblvt\onlinetime\core\formatter
        arguments:
            - @user
imports:
    - { resource: tables.yml }
