services:
    david63.logfailedlogins.listener:
        class: david63\logfailedlogins\event\listener
        arguments:
            - @config
            - @log
            - @user
            - @auth
            - @dbal.conn
        tags:
            - { name: event.listener }
