services:
    vse.topicpreview.manager:
        class: vse\topicpreview\core\topic_preview
        arguments:
            - @config
            - @dbal.conn
            - @dispatcher
            - @template
            - @user
            - %core.root_path%
            - @vse.topicpreview.trim_tools

    vse.topicpreview.trim_tools:
        class: vse\topicpreview\core\trim_tools
        arguments:
            - @config

    vse.topicpreview.listener:
        class: vse\topicpreview\event\listener
        arguments:
            - @vse.topicpreview.manager
        tags:
            - { name: event.listener }

    vse.topicpreview.ucp_listener:
        class: vse\topicpreview\event\ucp_listener
        arguments:
            - @config
            - @request
            - @template
            - @user
        tags:
            - { name: event.listener }
